### ISSUE TITLE
How to use this code?

### ISSUE THREAD

**Issue by billchen8888** [LukeMwila/aws-eks-platform#1]
Luke,

I come cross to your code but not sure how I can use it.  

If I try to do   terraform apply  in the aws-eks-platform/infra-modules/eks_environment/   folder,  I need to give value for eks_cluster_subnets   and   main_pvt_route_table_id   , but I don't know what values I should give as the VPC is not in place yet.  

So then I think I might need to  cd to aws-eks-platform/infra-modules/eks_environment/vpc/ and tun terraform apply to create the VPC first, but I am prompted to give value for main_pvt_route_table_id.  How could I know it as the VPC is not created yet?   This seems a deadlock or I miss something?

Thanks.

Bill

**Comment by LukeMwila** [comment]
Hi @billchen8888 , thanks for your question. I'm actually planning on deprecating this repo because it's poorly structured and not easy to get up and running. I recently created a better and more stable setup with a clear README here: https://github.com/LukeMwila/amazon-eks-cluster. Please have a look and let me know if you have any issues.

**Comment by billchen8888** [comment]
> Hi @billchen8888 , thanks for your question. I'm actually planning on deprecating this repo because it's poorly structured and not easy to get up and running. I recently created a better and more stable setup with a clear README here: https://github.com/LukeMwila/amazon-eks-cluster. Please have a look and let me know if you have any issues.

@LukeMwila  Thanks for the quick response!  Really appreciate your great work and I will give a try with the new one you mentioned. Just for your info - I came cross to your previous code from the article 

https://blog.devgenius.io/create-an-amazon-eks-cluster-with-managed-node-group-using-terraform-a3b50d276b13

Thanks and have a good one!

**Comment by LukeMwila** [comment]
Thanks @billchen8888 , I'm going to close this. If you have any issues with the new repo, please create them on that repository :)
